package com.example.ais_store.Commands;

public enum Commands {
    ADD_PRODUCT,
    ADD_CATEGORY,

    DELETE_PRODUCT_BY_ID,
    DELETE_CATEGORY_BY_ID,

    UPDATE_PRODUCT_ID,
    UPDATE_PRODUCT_NAME,
    UPDATE_PRODUCT_CATEGORY,
    UPDATE_PRODUCT_PRICE,
    UPDATE_PRODUCT_NUMBER,

    UPDATE_CATEGORY_ID,
    UPDATE_CATEGORY_NAME
}
